name: Build and Deploy to GitHub Pages

# 이 워크플로우가 실행되는 트리거
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 열리거나 머지될 때 실행

# 워크플로우의 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest  # 사용할 가상 머신 환경

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 2. Node.js 및 pnpm 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      
      # 3. pnpm 설치
      - name: Install pnpm
        run: npm install -g pnpm
      
      # 4. 의존성 설치
      - name: Install dependencies
        run: pnpm install
      
      # 5. 빌드 실행
      - name: Run build
        run: pnpm build
      
      # 6. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions의 토큰을 사용
          publish_dir: ./dist  # 빌드된 파일이 위치한 디렉토리 경로 (pnpm build 결과물)

