name: Build and Deploy to GitHub Pages

# 이 워크플로우가 실행되는 트리거
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main  # main 브랜치에 대한 PR이 열리거나 머지될 때 실행

# 워크플로우의 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest  # 사용할 가상 머신 환경

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.0

      - uses: actions/cache@v4.0.2
        id: pnpm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.pnpm-cache.outputs.cache-hit != 'true'
        id: install
        run: pnpm install && echo "::set-output name=installed::true"

      - if: steps.install.outputs.installed != 'true'
        run: pnpm install
      
      # 5. 빌드 실행
      - name: Run build
        run: pnpm build
      
      # 6. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
